spring:
  redis:
    host: localhost
    port: 6379
#    password: yourpassword  # Redis密码，如果需要的话
    database: 0            # Redis数据库索引，默认为0
    lettuce:
      pool:
        max-active: 8      # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8        # 连接池中的最大空闲连接
        min-idle: 0        # 连接池中的最小空闲连接
        max-wait: -1ms     # 连接池最大阻塞等待时间（使用负值表示没有限制）
  mail:
    host: smtp.163.com
    port: 465 # 或者使用25端口，如果不使用SSL
    username: 13343387859@163.com
    password: BVfxjgvHmNkr9NqG # 这里填写你在第一步中获取的授权码
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465 # 如果使用SSL
  application:
    name: user-center-backend
  # DataSource Config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: qpzm79135
  # session 失效时间
  session:
    timeout: 86400
server:
  port: 8386
  servlet:
    context-path: /user
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


aliyun:
  sms:
    accessKeyId: "LTAI5tKfKGwzvtVEkYJCEkdX"
    accessSecret: "I0fP5udXR9K0oTGVJNQF3RWypXwRED"
    signName: "geology612"
    templateCode: "SMS_476890036"
    product: "Dysmsapi"
    domain: "dysmsapi.aliyuncs.com"